baseURL = "/"
title = "MediSync Solutions"
languageCode = "ru-ru"
defaultContentLanguage = "ru"
paginate = "7"
theme = "spectral"

[params]
fancyTitle = "MediSync Solutions" # title for frontpage, may include image
copyright = "MediSync team"
description = 'Сервис управления сбором и анализа данных персонализированной медицины'
startbuttonText = "Запись на бета тест"
startbuttonLink = "#contact"
body_is_markdown = true
#custom_css = "foo.css"
#images = ["path_to_social_image_for_link_previews.jpg"]

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/posts/'
title = "Posts"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'Arcu aliquet vel lobortis ata nisl<br />eget augue amet aliquet nisl cep donec'
body = '''
Aliquam ut ex ut augue consectetur interdum. Donec amet imperdiet eleifend  
fringilla tincidunt. Nullam dui leo Aenean mi ligula, rhoncus ullamcorper.
'''

[[params.one.icon]]
icon = "fa-gem"
style = "1"
label = "Lorem"

[[params.one.icon]]
icon = "fa-heart"
style = "2"
label = "Ipsum"

[[params.one.icon]]
icon = "solid fa-code"
style = "3"
label = "Dolor"

[params.two]
enable = true

[[params.two.section]]
img = "img/pic01.jpg"
img_alt = "blurry background: white/grey"
title = 'Magna primis lobortis<br />sed ullamcorper'
body = 'Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.'

[[params.two.section]]
img = "img/pic02.jpg"
title = 'Tortor dolore feugiat<br />elementum magna'
body = 'Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.'

[[params.two.section]]
img = "img/pic03.jpg"
title = 'Magna primis lobortis<br />sed ullamcorper'
body = 'Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.'

[params.three]
enable = true
title = 'Асхаб тамаев'
body = '''
я не химик я не химик я не химик
'''

[[params.three.feature]]
icon = "fa-paper-plane"
title = "Залупа"
body = "использование носимых и мобильных устройств"

[[params.three.feature]]
icon = "solid fa-laptop"
title = "залупа 2"
body = "индивидуальные особенности взаимодействия в системах с человеко-машинным интерфейсом (HMI)"

[[params.three.feature]]
icon = "solid fa-code"
title = "залупа 3"
body = "оценка сенсомоторных рассогласований"

[[params.three.feature]]
icon = "solid fa-headphones-alt"
title = "придумали хуйни"
body = "выявление психо-эмоциональных параметров"

[[params.three.feature]]
icon = "fa-heart"
title = "тройник 220v"
body = "цифровые двойники"

[[params.three.feature]]
icon = "fa-flag"
title = "Калекие клетик ктик тки"
body = "- Доводилось ли вам бывать в тюрьме? Клетки.- Клетки.- Вас держат в клетке? Клетки.- Клетки.- Когда вы не исполняете обязанности, вас держат в коробке? Клетки.- Клетки.- Связаны.- Связаны.- Что вы чувствуете держа за руку того кого любите? Связаны.- Связаны.- Вас учили приставлять палец к пальцу? Связаны.- Связаны.- Вы жаждете связать с кем-нибудь сердце? Связаны.- Связаны.- Вам снится связь с кем-либо? Связаны.- Связаны.- Что вы чувствуете, держа в руках своего ребенка? Связаны.- Связаны.- Вы чувствуете, что вам чего-то не хватает?- Связаны.- Клеток связанных внутри.- Клеток связанных внутри.- Повторите три раза клеток связанных внутри- Клеток связанных внутри. Клеток связанных внутри. Клеток связанных внутри."

[params.cta]
enable = false
title = "Arcue ut vel commodo"
body = "Aliquam ut ex ut augue consectetur interdum endrerit imperdiet amet eleifend fringilla."

[[params.cta.link]]
href = "#contact"
text = "Запись на бета тест"
special = true

[[params.cta.link]]
href = "#"
text = "Узнать больше"
special = false

[params.contact]
enable = true
title = "Запишитесь на бета тест"
body = "Оставьте свою заявку тут"
phone = "+7 (0) 030 000 000"
address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
email = "nospam@example.com"
subject = "New Submission!"
formspree_form_id = "example_invalid"

[params.social]
twitter = ""
mastodon = ""
github = ""
facebook = ""
youtube = ""
instagram = ""
dribble = ""

# language specific options

[languages.ru]
weight = 0
languageName = "Русский"
